[project]
name = "fastapi-url-shortener"
version = "0.1.0"
description = "Url script shortener"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "uvicorn<=0.20.0"
]

