name: Python checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "url-shortener/**"

jobs:

  run-code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v5

      - name: 2. Download python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: 3. Install Blackâ¬›
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

      - name: 4. Black check
        run: |
          black --check --diff ./

      - name: 5. Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: 'pyproject.toml'
          enable-cache: true

      - name: 6. Install the project
        run: uv sync --locked --all-extras --dev

      - name: 7. Run ruff --dif
        uses: astral-sh/ruff-action@v3
        with:
          args: 'check --diff'
          version-file: "pyproject.toml"

      - name: 8. run mypy
        run: uv run mypy url-shortener

  run-tests:
    runs-on: ubuntu-latest
    needs:
      - run-code-style-check
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v5

      - name: 2. Download python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: 3. Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: 'pyproject.toml'
          enable-cache: true

      - name: 4. Install the project
        run: uv sync --locked --all-extras --dev

      - name: 5. Run python pytest
        run: uv run pytest url-shortener --cov-report=json:coverage.json --cov=url-shortener --cov-report=xml:coverage.xml
        env:
          TESTING: 1
          REDIS_PORT: 6379

      - name: 6. Upload coverage reports artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage.json
          retention-days: 1

  update-coverage-badge:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: 1. Downloads coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports

      - name: 2. Prepare coverage percentage
        run: |
          export EXTRACTED_COVERAGE=$(python -c 'import json;print(json.load(open("coverage.json"))["totals"]["percent_covered_display"])')
          echo "TOTAL_COVERAGE=$EXTRACTED_COVERAGE" >> $GITHUB_ENV
          echo "### Tests coverage: {$EXTRACTED_COVERAGE}%" >> $GITHUB_STEP_SUMMARY

      - name: 3. Update coverage badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 8ccc9117a4a81627856cb5d379113e0f
          filename: coverage.json
          label: Coverage
          message: ${{env.TOTAL_COVERAGE}}%
          minColorRange: 70
          maxColorRange: 90
          valColorRange: ${{ env.TOTAL_COVERAGE}}


  upload-to-codecov:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: 1. Downloads coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports

      - name: 2. Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        if: ${{ !github.event.act }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          dry_run: ${{ env.ACT }}
          fail_ci_if_error: 'true'
