name: Python checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "url-shortener/**"

jobs:

  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # скачиваем код в раннер
        uses: actions/checkout@v5
      - uses: actions/setup-python@v5 # скачиваем питон из кеша гитхаб
        with:
          python-version-file: '.python-version' # вот отсюда берем версию питона

      - name: Install Black⬛
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"
      - name: Black # проверяем блеком
        run: |
          black --check --diff ./

      - name: Setup UV # установка UV
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: 'pyproject.toml' # файл с настройками
          enable-cache: true
      - name: Install the project # установка зависимостей
        run: uv sync --locked --all-extras --dev

      - name: Run ruff --dif # запуск ruff c показом ошибок
        uses: astral-sh/ruff-action@v3
        with:
          args: 'check --diff'
          version-file: "pyproject.toml"
      - name: Run ruff # запуск ruff стандарт, чтобы показать что все ок
        uses: astral-sh/ruff-action@v3
        with:
          version-file: "pyproject.toml"

      - name: run mypy # запуск mypy через UV
        run: uv run mypy url-shortener
